### ISSUE TITLE
[Anon] Bug report: SPQR.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/spqr#1]
**File:** SPQR.gstz

**BattleScribe version:** 2.02.03

**Platform:** Android

**Dropbox:** No

**Description:** There are five missing entries in the Talents section. Under the Talents Section, there are five missing entries for the "Archer of Legend" section. (Missing Talents: Crippling Shot; Precision Shot; Armour Cracker; Critical Shot; One Arrow, One Kill) Reference page 42 in the SPQR rule book for further notes.

**Comment by mugginns-zz** [comment]
Hi, these talents are part of a tree and will show up if you select the first talent in the tree. Thanks
