### ISSUE TITLE
Germania.catz

### ISSUE THREAD

**Issue by ToyoKogyo** [BSData/spqr#12]
Germania's options appear to be a mirror of Gaul.

- Wardogs and a Druid shouldn't be options
- Warriors can't take swords and short spears are the default

I did make the adjustments to the file I have. I can send it in if needed.

**Comment by mugginns-zz** [comment]
I'll be honest, I haven't played SPQR. I put together the file but haven't played yet. If you'd like I can see about adding you to the team to make changes.

**Comment by ToyoKogyo** [comment]
That would work for me!

Edit: As in I'd be fine contributing to the team if possible.

**Comment by mugginns-zz** [comment]
@mugginns Can @ToyoKogyo open a [Join Request] issue in the repo for me? I prefer to have these things tracked like that. :)
As per https://github.com/BSData/catalogue-development/wiki/Joining-Repository#warlord-games

**Comment by amis92** [comment]
This issue is stale and most probably no longer useful. If you want to continue this discussion, please reopen this issue or create a new one.

Thank you.
