### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by thebigandyt** [BSData/spqr#17]
Hi all, i was looking to see if i could help update SPQR, not a programmer but plenty experience as working as software tester so not completely new to development(close to it mind)

**Comment by Mad-Spy** [comment]
It looks like it's been abandoned by the current maintainer so you're welcome to get stuck in.

**Comment by Mad-Spy** [comment]
/invite

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/1712361653)
:robot: Invited @thebigandyt with **push** access. Invite can be accepted on https://github.com/BSData/spqr/invitations

**Comment by thebigandyt** [comment]
Thanks Iain, I gave it whirl. Think it went ok. Did a release, I think
