### ISSUE TITLE
Athenian Peltasts

### ISSUE THREAD

**Issue by Garthbo** [BSData/spqr#2]
Hi - 

In the SPQR Athenian list, taking any additional Javelins gives an error.

Thanks,
Larry
![84FBCB2C-204E-4715-8661-47D5377087F2](https://user-images.githubusercontent.com/3686160/62712497-f36b3d00-b9c8-11e9-9860-1328fdfc2430.jpeg)
![5B13463B-FCBC-4013-8B19-D1212BE390A4](https://user-images.githubusercontent.com/3686160/62712521-0120c280-b9c9-11e9-8540-f01e46dcccb1.jpeg)

**Comment by mugginns-zz** [comment]
Hi, I can't reproduce this. Maybe I fixed it with another release? Not sure
